### ISSUE TITLE
Package Encryption

### ISSUE THREAD

**Issue by Haltroy** [Haltroy/Foster#1]
Currently, Foster does not encrypt packages with anything. Foster can easily encrypt and decrypt using new add-ons named "encryptions".
Foster can also detect the encryption method used in the package and ask a password for encrypting the package. If the password was correct, Foster can apply the package. If not, Foster can just stop the process.
**TODOs:**
 - [x] Add encryption support.
 - [x] Add decryption support.
 - [x] Add new header information.
