### ISSUE TITLE
Release Notification - Foster 2.1

### ISSUE THREAD

**Issue by Haltroy** [Haltroy/Foster#15]
# Important

This update might come late (and might even in the next years) but I will try my best to focus on it. However, since Foster 2.0 was stable enough I think implementing these would be easy.

# TODOs

**Easy**
- [ ] #14 
- [ ] #12 

**Medium**
- [ ] #13 
- [ ] #10

**Aftermath**
- [ ] Release new documentation
- [ ] Release new API docs
- [ ] Release to NuGet
