### ISSUE TITLE
Extend the Compression

### ISSUE THREAD

**Issue by Haltroy** [Haltroy/Foster#2]
Currently, Foster can only compress 4GiB of data, this is the limit of GZip and Deflate algorithms. This data includes the binaries of each file, the file names encoded in UTF-18 Little Endian and a Int64 of each file size. If it's a delta package, things can get messy.

Foster can divided the base stream (that contains the raw information) and split into small 1GiB pieces and compress them. Also, Foster can check the header to get additional information and do decompression with that information.

Also, Foster can just do it in normal way if the package is smaller than 1GiB.

**TODOs:**
 - [x] Stop using memory stream, just use the file stream itself so we won't be limited to the RAM size.
 - [x] Add multi-part compression.
 - [x] Add compressed length to each while copying them from one stream to another.
 - [x] Add information to header.
 - [x] Add to decompression.
 - [x] Add dates to files.

**Comment by Haltroy** [comment]
whoops forgot one
