### ISSUE TITLE
Release Notification - Foster 2.0

### ISSUE THREAD

**Issue by Haltroy** [Haltroy/Foster#6]
# Important

The namespace is changed from `Foster` to `LibFoster` to avoid `Foster.Foster` and just use `Foster`. So change your `using Foster;` or `Imports Foster` to `using LibFoster;` or `Imports LibFoster`.

The Foster Packer and Foster is now combined and there are only `Read` and `Write` options. Yo ucan call `Write` method with `HeaderContext` and `Read` with either the Foster itself or a path. 

The Xml parser is no longer the default parser. The binary parser is the new default parser. The Xml parser can be found on [this repository](https://github.com/Haltroy/FosterParserXml).

Foster now supports encryption and file sizes more than 4GiB.

We changed the license from GNU GPL v3.0 to MIT License so more people can use it.

# TODO:
 - [x] #1 
 - [x] #2 
 - [x] #3 
 - [x] Finish TODOs.
 - [x] #8 
 - [x] Test the new features.
 - [x] Release the new version.
 - [x] Generate API documents.
 - [x] Improve website.
 - [x] Release Format document.

**Comment by Haltroy** [comment]
[Here's the draft version of the Foster format.](https://github.com/Haltroy/Foster/files/8366542/Foster.Package.Format.docx)
